aqm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from aqm.apps.sensors.urls import urlpatterns as sensor_urls

urlpatterns = [
    path('sensors', include('aqm.apps.sensors.urls', namespace='sensors')),

    # Admin-y stuff
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path('batcave/', admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls))
    ]
    # urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

camp/api/urls.py
from django.urls import include, path
from django.views import generic

from resticus.views import get_schema_view

from .v1 import urls as urls_v1_0

app_name = 'api'

schema_v1_0 = get_schema_view(
    title="SJVAir API v1.0", prefix="/api/1.0/", urlconf=urls_v1_0
)

urlpatterns = [
    path('2.0/', include('camp.api.v2.urls', namespace='v2')),

    path('1.0/', include('camp.api.v1.urls', namespace='v1')),
    path('1.0/schema/', schema_v1_0, name="schema_v1_0"),
    path('1.0/swagger/',
        generic.TemplateView.as_view(
            template_name="swagger/index.html",
            extra_context={"schema_url": "api:schema_v1_0"},
        ),
        name="swagger",
    ),
]

camp/api/v1/urls.py
from django.urls import include, path

from . import endpoints
from .alerts.endpoints import SubscriptionList

app_name = 'api'

urlpatterns = [
    path('time/', endpoints.CurrentTime.as_view(), name='current-time'),
    path('alerts/subscriptions/', SubscriptionList.as_view(), name='subscription-list'),

    path('account/', include('camp.api.v1.accounts.urls', namespace='account')),
    path('monitors/', include('camp.api.v1.monitors.urls', namespace='monitors')),
    path('calibrations/', include('camp.api.v1.calibrations.urls', namespace='calibrations')),
    path('marker.png', endpoints.MapMarker.as_view(), name='marker'),

]

camp/apps/helpdesk/urls.py
from django.urls import path

from .views import Home, CategoryDetail, ArticleDetail, Glossary, Search

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('category/<str:sqid>/<str:slug>/', CategoryDetail.as_view(), name='category-detail'),
    path('article/<str:sqid>/<str:slug>/', ArticleDetail.as_view(), name='article-detail'),
    path('glossary/', Glossary.as_view(), name='glossary'),
    path('search/', Search.as_view(), name='search'),
]

camp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path

from camp.utils import views

admin.site.site_title = "SJVAir Admin"
admin.site.site_header = "SJVAir Admin"

urlpatterns = [
    path('api/', include('camp.api.urls', namespace='api')),
    path('account/', include(('camp.apps.accounts.urls', 'account'), namespace='account')),
    path('contact/', include(('camp.apps.contact.urls', 'contact'), namespace='contact')),
    path('support/', include(('camp.apps.helpdesk.urls', 'helpdesk'), namespace='helpdesk')),
    path('app/', views.GetTheApp.as_view(), name='app'),

    # @sjvair/monitor-map specific routes
    path('monitor/<monitor_id>/', views.PageTemplate.as_view(template_name='pages/index.html')),
    path('widget/', views.RenderStatic.as_view(static_file='widget/index.html')),

    path('prose/', include('prose.urls')),

    # Admin-y stuff
    path('system-status/', include('health_check.urls')),
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path('batcave/stats.json', views.AdminStats.as_view(), name='admin-stats'),
    path('batcave/flush-queue/<str:key>/', views.FlushQueue.as_view(), name='flush-queue'),
    path('batcave/silk/', include('silk.urls', namespace='silk')),
    path('batcave/', admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Catch-all to render templates based on the path
urlpatterns += [re_path('^', views.PageTemplate.as_view())]

camp/apps/accounts/models.py
import random
import string

from django.conf import settings
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.core.cache import cache
from django.db import models
from django.utils import timezone
from django.utils.functional import cached_property
from django.utils.translation import gettext_lazy as _

from dirtyfields import DirtyFieldsMixin
from django_smalluuid.models import SmallUUIDField, uuid_default
from model_utils import Choices
from nameparser.parser import HumanName
from phonenumber_field.modelfields import PhoneNumberField

from camp.apps.accounts import managers
from camp.apps.accounts import tasks
from camp.utils.fields import NullEmailField


class User(AbstractBaseUser, PermissionsMixin, DirtyFieldsMixin, models.Model):
    LANGUAGES = Choices(*settings.LANGUAGES)

    id = SmallUUIDField(
        default=uuid_default(),
        primary_key=True,
        db_index=True,
        editable=False,
        verbose_name='ID'
    )
    full_name = models.CharField(_('Full name'), max_length=100)
    email = NullEmailField(_('Email address'), unique=True, blank=True, null=True, db_index=True)
    phone = PhoneNumberField(_('Phone number'), unique=True, db_index=True, help_text="Your cell phone number for receiving air quality text alerts.")
    phone_verified = models.BooleanField(default=False)
    language = models.CharField(_('Preferred Language'), max_length=5, choices=LANGUAGES, default=LANGUAGES.en)

    # Normally provided by auth.AbstractUser, but we're not using that here.
    date_joined = models.DateTimeField(_('Date joined'), default=timezone.now, editable=False)
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as '
            'active. Unselect this instead of deleting accounts.'
        )
    )
    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_(
            'Designates whether the user can log into this admin site.'
        )
    )

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'phone'
    REQUIRED_FIELDS = ['full_name']

    objects = managers.UserManager()

    class Meta:
        ordering = ('-date_joined',)

    def __str__(self):
        return str(self.name)

    def get_name(self):
        name = HumanName(self.full_name)
        name.capitalize()
        return name

    def set_name(self, value):
        self.full_name = value
        del self.name

    name = cached_property(get_name)
    name.setter = set_name

    def get_short_name(self):
        return self.name.first

    def get_full_name(self):
        return self.name

    @property
    def phone_verification_rate_limit_key(self):
        return f'phone-rate-limit:{self.phone}'

    @property
    def phone_verification_code_key(self):
        return f'phone-code:{self.phone}'

    def check_phone_verification_rate_limit(self):
        cache_key = self.phone_verification_rate_limit_key
        return cache.get(cache_key, default=False)

    def set_phone_verification_rate_limit(self):
        cache_key = self.phone_verification_rate_limit_key
        expires = settings.PHONE_VERIFICATION_RATE_LIMIT * 60
        cache.set(cache_key, True, expires)

    def send_phone_verification_code(self):
        expires = settings.PHONE_VERIFICATION_CODE_EXPIRES * 60
        code = ''.join([
            random.choice(string.digits) for x
            in range(settings.PHONE_VERIFICATION_CODE_DIGITS)
        ])
        cache.set(self.phone_verification_code_key, code, expires)
        message = f'SJVAir – Verification Code: {code}'
        self.send_sms(message, verify=False)  # Don't do a verification check

    def check_phone_verification_code(self, code):
        cached_code = cache.get(self.phone_verification_code_key)
        return code == cached_code

    def send_sms(self, message, verify=True):
        if self.phone and (self.phone_verified or not verify):
            return tasks.send_sms_message(self.phone, message)
        return False

camp/apps/alerts/models.py
from datetime import timedelta

from django.conf import settings
from django.core.exceptions import ValidationError
from django.db import models
from django.db.models import Avg
from django.utils import timezone
from django.utils.functional import cached_property
from django.utils.translation import gettext as _

from django_smalluuid.models import SmallUUIDField, uuid_default
from model_utils import Choices
from model_utils.models import TimeStampedModel

from camp.apps.entries.fields import EntryTypeField
from camp.apps.entries.levels import AQLevel


class Subscription(TimeStampedModel):
    LEVELS = Choices(  # Legacy
        ('unhealthy_sensitive', 'Unhealthy for Sensitive Groups'),
        ('unhealthy', 'Unhealthy'),
        ('very_unhealthy', 'Very Unhealthy'),
        ('hazardous', 'Hazardous'),
    )

    id = SmallUUIDField(
        default=uuid_default(),
        primary_key=True,
        db_index=True,
        editable=False,
        verbose_name='ID'
    )

    user = models.ForeignKey('accounts.User',
        related_name='subscriptions',
        on_delete=models.CASCADE,
    )

    monitor = models.ForeignKey('monitors.Monitor',
        related_name='subscriptions',
        on_delete=models.CASCADE,
    )

    level = models.CharField(max_length=25, choices=AQLevel.choices)

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'monitor'],
                name='user_subscriptions'
            )
        ]

        ordering = ['monitor__name']

    def __str__(self):
        return f'{self.user_id} : {self.monitor_id} @ {self.level}'

    def clean(self):
        super().clean()
        self.level = self.level.lower()


class Alert(TimeStampedModel):
    id = SmallUUIDField(
        default=uuid_default(),
        primary_key=True,
        db_index=True,
        editable=False,
        verbose_name='ID'
    )

    monitor = models.ForeignKey('monitors.Monitor', related_name='alerts', on_delete=models.CASCADE)
    entry_type = EntryTypeField()

    start_time = models.DateTimeField()
    end_time = models.DateTimeField(blank=True, null=True)

    latest = models.OneToOneField(
        'alerts.AlertUpdate',
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='+'
    )

    class Meta:
        ordering = ['-start_time']

    def __str__(self):
        return f'Alert for {self.monitor_id} ({self.entry_type}) @ {self.start_time}'

    @cached_property
    def entry_model(self):
        return EntryTypeField.get_model_map().get(self.entry_type)

    def get_average(self, hours=1):
        end_time = timezone.now()
        start_time = end_time - timedelta(hours=hours)
        return (self.monitor.entries
            .filter(timestamp__range=(start_time, end_time))
            .aggregate(average=Avg('pm25'))['average']
        )

    def create_update(self, level, **kwargs):
        update = AlertUpdate.objects.create(
            alert_id=self.pk,
            level=level.key,
            **kwargs,
        )
        self.send_notifications(update.get_level())
        return update

    def send_notifications(self, level):
        # If SMS alerts are disbaled, do nothing.
        if not settings.SEND_SMS_ALERTS:
            return

        icon = '✅' if level == AQLevel.scale.GOOD else '⚠️'
        message = '\n'.join([
            _('{icon} Air Quality Alert for {name} in {county} County').format(
                icon=icon,
                name=self.monitor.name,
                county=self.monitor.county,
            ),
            f'{self.entry_model.label}: {level.label}',
            f'{level.guidance}\n' or '',
            f'🔗 https://sjvair.com{self.monitor.get_absolute_url()}',
        ])

        queryset = (Subscription.objects
            .filter(monitor_id=self.monitor.pk)
            .select_related('user')
        )

        for sub in queryset:
            sub_level = AQLevel.scale[sub.level.upper()]
            if level >= sub_level:
                sub.user.send_sms(message)


class AlertUpdate(TimeStampedModel):
    alert = models.ForeignKey('alerts.Alert', related_name='updates', on_delete=models.CASCADE)
    timestamp = models.DateTimeField(default=timezone.now)
    level = models.CharField(max_length=25)

    class Meta:
        get_latest_by = 'timestamp'
        ordering = ['timestamp']

    def __str__(self):
        return f'AlertUpdate for {self.alert_id} @ {self.timestamp} => {self.level}'

    def get_level(self):
        return self.alert.entry_model.Levels[self.level]

    def clean(self):
        if not self.alert.entry_model or not self.alert.entry_model.Levels:
            raise ValidationError('This alert entry type does not support alert levels.')

        if self.alert.entry_model.Levels.lookup(self.level) is None:
            raise ValidationError(f'{self.level} is not a valid alert level for {self.alert.entry_type.label}.')

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if not self.alert.latest or self.alert.latest.timestamp < self.timestamp:
            self.alert.latest_id = self.pk
            self.alert.save(update_fields=['latest_id'])

camp/apps/integrate/hms_smoke/models.py
from django.contrib.gis.db import models as gis_models
from django.db import models
from django_smalluuid.models import SmallUUIDField, uuid_default


"""
Defines the database for holding HMS Wildfire smoke data.
This includes:
    the start/end time of the plume: stored as datetime objects
    satellite: the satellite used to observe the smoke
    density: density of smoke plume ("Light", "Medium", or "Heavy")
    geometry: polygonal smoke region in standard GPS coordinates (srid = 4326)
    ID: unique database ID identifier   
"""


class Smoke(models.Model):
    class Density(models.TextChoices):
        LIGHT = 'light', 'Light'
        MEDIUM = 'medium', 'Medium'
        HEAVY = 'heavy', 'Heavy'
    
    id = SmallUUIDField(
        default=uuid_default(),
        primary_key=True,
        db_index=True,
        editable=False,
        verbose_name='ID'
    )
    date = models.DateField(null=True)
    satellite = models.CharField(max_length=20)
    start = models.DateTimeField(null=True)
    end = models.DateTimeField(null=True) 
    density = models.CharField(max_length=10, choices=Density.choices, default=Density.LIGHT)
    geometry = gis_models.MultiPolygonField(srid=4326)
    is_final = models.BooleanField(default=False)

camp/apps/integrate/tempo/models.py
from django.db import models
from django_smalluuid.models import SmallUUIDField, uuid_default



def file_path(instance, filename):
    return f"observations/{instance.pollutant}/{instance.timestamp:%Y%m%d%H%M%S}/{filename}"

class TempoGrid(models.Model):
    class Pollutant(models.TextChoices):
        O3TOT = 'o3tot', 'Ozone' #measured in Dobson Units   range is <1.00e+02 DU to  >=4.97e+02DU
        HCHO = 'hcho', 'Formaldehyde' #measured in molecules/cm2   range is <0 mol/cm2 to >=2.94e+16 mol/cm2
        NO2 = 'no2', 'Nitrogen Dioxide' #measured in molecules/cm2   range is <0 mol/cm2 to >=2.99e+16 mol/cm2
        
    id = SmallUUIDField(
        default=uuid_default(),
        primary_key=True,
        db_index=True,
        editable=False,
        verbose_name='ID'
    )
    
    
    pollutant = models.CharField(max_length=5, choices=Pollutant.choices,)
    timestamp = models.DateTimeField(null=True)
    timestamp_2 = models.DateTimeField(null=True, blank=True)

    file = models.FileField(upload_to=file_path, null=True, blank=True)
    
    final = models.BooleanField()

camp/api/v1/forms.py
import re

from django import forms
from django.core.validators import RegexValidator
from django.utils.translation import gettext_lazy as _

COLOR_RE = re.compile('^([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')
color_validator = RegexValidator(COLOR_RE, _('Enter a valid color.'), 'invalid')


class MarkerForm(forms.Form):
    size = forms.IntegerField(initial=24, required=False)
    shape = forms.ChoiceField(choices=[
        (x, x) for x in ('square', 'circle', 'polygon')
        ], initial='circle', required=False)
    fill_color = forms.CharField(validators=[color_validator], initial='777', required=False)
    border_color = forms.CharField(validators=[color_validator], initial='000', required=False)
    border_size = forms.IntegerField(initial=0, required=False)
    sides = forms.IntegerField(initial=3, required=False)

    def get_defaults(self):
        return {key: field.initial for key, field in self.fields.items()}

    def get_data(self):
        data = self.get_defaults()
        if self.is_valid():
            for key, value in self.cleaned_data.items():
                if value:
                    data[key] = value
        return data

camp/api/v1/monitors/forms.py
from django import forms

from camp.apps.monitors.models import Entry


class EntryForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['timestamp'].required = False

        for key in Entry.ENVIRONMENT:
            self.fields[key].required = False

    class Meta:
        model = Entry
        fields = ['timestamp', 'sensor'] + Entry.ENVIRONMENT

camp/templates/helpdesk/article-detail.html
{% extends 'helpdesk/base.html' %}
{% load static %}
{% load sjvair %}

{% block title %}{{ article.title }} | {{ block.super }}{% endblock %}

{% block body-class %}{{ block.super }} article-detail{% endblock %}

{% block breadcrumb-list %}
    <li>
        <a href="{{ article.category.get_absolute_url }}">{{ article.category.name }}</a>
    </li>
    <li class="is-active">
        <a href="{{ article.get_absolute_url }}">{{ article.title }}</a>
    </li>
{% endblock %}

{% block content %}
<section class="section">
    <div class="container">
        <div class="columns">
            <div class="column is-full-tablet is-8-desktop">
                <div class="content">
                    <h1>{{ article.title }}</h1>
                    <p class="is-size-7 is-italic">Last updated {{ article.modified|date }}</p>
                    {{ article.content|safe }}
                </div>
                {% if related_articles or related_terms %}
                <div class="columns">
                    {% if related_articles %}
                    <div class="column is-full-tablet is-half-desktop">
                        <div class="card related-articles">
                            <header class="card-header">
                                <p class="card-header-title">Related Articles</p>
                            </header>
                            <div class="card-content">
                                {% include "helpdesk/includes/article-list-inline.html" with article_list=related_articles show_featured=True %}
                            </div>
                        </div>
                    </div>
                    {% endif %}

                    {% if related_terms %}
                    <div class="column is-full-tablet is-half-desktop">
                        <div class="card related-terms">
                            <header class="card-header">
                                <p class="card-header-title">Related Terms</p>
                            </header>
                            <div class="card-content">
                                {% include "helpdesk/includes/term-list-inline.html" with term_list=related_terms %}
                            </div>
                        </div>
                    </div>
                    {% endif %}
                </div>
                {% endif %}
            </div>
            <div class="column is-full-tablet is-4-desktop side-column">
                {% include 'helpdesk/includes/category-detail-card.html' with category=article.category show_featured=True active=article.pk %}

                {% include 'helpdesk/includes/cta-contact.html' %}
            </div>
        </div>
    </div>
</section>

{% endblock %}

camp/templates/helpdesk/base.html
{% extends 'page.html' %}
{% load static %}
{% load sjvair %}

{% block title %}Help Center | {{ block.super }}{% endblock %}

{% block body-class %}helpdesk{% endblock %}

{% block main %}
<section class="section is-small hook">
    <div class="container">
        {% block search_header %}
        <div class="content">
            <h1 class="is-size-2">Help Center</h1>
            <form action="{% url 'helpdesk:search' %}" method="GET" class="form search is-inline-block">
                <div class="field is-grouped">
                    <p class="control has-icons-left">
                        <input type="text" name="q" value="{{ search_query }}" class="input is-large" placeholder="Search...">
                        <span class="icon is-small is-left">
                            <span class="fas fa-search"></span>
                        </span>
                    </p>
                    <p class="control">
                        <button class="button is-large is-dark">Search</button>
                    </p>
                </div>
            </form>
        </div>
        {% endblock %}
    </div>
</section>

{% block breadcrumbs %}
<section class="breadcrumbs">
    <div class="container">
        <nav class="breadcrumb" aria-label="breadcrumbs">
            <ul>
                <li><a href="{% url 'helpdesk:home' %}">Help Center</a></li>
                {% block breadcrumb-list %}{% endblock %}
            </ul>
        </nav>
    </div>
</section>
{% endblock %}
{% block content %}{% endblock %}

{% endblock %}

camp/templates/helpdesk/category-detail.html
{% extends 'helpdesk/base.html' %}
{% load static %}
{% load sjvair %}

{% block title %}{{ category.name }} | {{ block.super }}{% endblock %}

{% block body-class %}{{ block.super }} category-detail{% endblock %}

{% block breadcrumb-list %}
    <li class="is-active">
        <a href="{{ category.get_absolute_url }}" aria-current="page">{{ category.name }}</a>
    </li>
{% endblock %}

{% block content %}
<section class="section">
    <div class="container">
        <div class="columns">
            <div class="column is-8-desktop">
                <div class="content">
                    <h1>{{ category.name }}</h1>
                    {% include "helpdesk/includes/article-list-inline.html" with article_list=articles show_featured=True %}
                </div>
            </div>
            <div class="column is-4-desktop side-column">
                {% include 'helpdesk/includes/category-list-card.html' with categories=categories active=category.pk %}

                {% include 'helpdesk/includes/cta-contact.html' %}
            </div>
        </div>
    </div>
</section>
{% endblock %}

camp/templates/helpdesk/glossary.html
{% extends 'helpdesk/base.html' %}
{% load static %}
{% load sjvair %}

{% block title %}Glossary | {{ block.super }}{% endblock %}

{% block body-class %}{{ block.super }} glossary{% endblock %}

{% block breadcrumb-list %}
    <li class="is-active">
        <a href="{% url 'helpdesk:glossary' %}">Glossary</a>
    </li>
{% endblock %}

{% block content %}
<section class="section">
    <div class="container">
        <div class="content">
            <h1>Glossary</h1>

            {% regroup term_list by slug|slice:":1"|upper as letter_list %}
            <div class=" content">
                <!-- <p class="has-text-weight-bold is-size-5">Skip to Letter</p> -->
                <div class="buttons">
                    {% for letter in letter_list %}
                    <a href="#{{ letter.grouper }}" class="button is-white has-text-weight-semibold">{{ letter.grouper }}</a>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="columns">
            <div class="column is-9-desktop">
                {% for letter in letter_list %}
                <div class="columns">
                    <div class="column is-1">
                        <a href="#{{ letter.grouper }}" id="{{ letter.grouper }}" class="has-text-weight-bold has-text-dark is-size-3">{{ letter.grouper }}</a>
                    </div>
                    <div class="column">
                        <ul class="list">
                            {% for term in letter.list %}
                            <li class="list-item box">
                                <div class="list-item-content">
                                    <div class="list-item-title">
                                        <a href="{{ term.get_absolute_url }}" id="{{ term.slug }}">{{ term.name }}</a>
                                        {% if term.synonyms %}
                                            <span class="has-text-grey has-text-weight-medium is-italic">({{ term.synonyms|join:", " }})</span>
                                        {% endif %}
                                    </div>
                                    <div class="list-item-description">
                                        <div class="content">
                                            {{ term.definition|safe }}
                                            {% if term.related_terms_count %}

                                            <p class="notification is-size-7 mt-3 p-2">See also: {% for rt in term.related_terms.all %}<a href="{{ rt.get_absolute_url }}" class="has-text-weight-medium">{{ rt.name }}</a>{% if not forloop.last %}, {% endif %}{% endfor %}</p>

                                            {% endif %}
                                        </div>
                                    </div>
                                </div>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
                {% endfor %}
            </div>
            <div class="column">
                {% include 'helpdesk/includes/cta-contact.html' %}
            </div>
        </div>
    </div>
</section>
{% endblock %}

camp/templates/helpdesk/home.html
{% extends 'helpdesk/base.html' %}
{% load static %}
{% load sjvair %}

{% block body-class %}{{ block.super }} home{% endblock %}

{% block breadcrumbs %}{% endblock %}

{% block search_header %}
    <div class="content has-text-centered">
        <h1 class="is-size-1">Help Center</h1>
        <p class="lead">Search our knowledge base or browse the content below</p>
        <form action="{% url 'helpdesk:search' %}" method="GET" class="form search is-inline-block">
            <div class="field is-grouped">
                <p class="control has-icons-left">
                    <input class="input is-large" type="text" name="q" placeholder="Search...">
                    <span class="icon is-small is-left">
                        <span class="fas fa-search"></span>
                    </span>
                </p>
                <p class="control">
                    <button class="button is-large is-dark">Search</button>
                </p>
            </div>
        </form>
    </div>
    {% endblock %}

{% block content %}
<section class="section faq has-background-white">
    <div class="container">
        <h2 class="is-size-4 has-text-weight-semibold">
            <span class="fas fa-fw fa-question-circle has-text-primary"></span>
            <span>Frequently Asked Questions</span>
        </h2>
        <div class="list masonry is-2-tablet is-2-desktop article-list">
            {% for article in feature_list %}
            <div class="list-item masonry-item">
                <div class="list-item-content">
                    <a href="{{ article.get_absolute_url }}">
                        <span class="fal fa-fw fa-file-alt has-text-dark"></span>
                        <span>{{ article.title }}</span>
                    </a>
                </div>
            </div>
            {% endfor %}
        </div>

    </div>
</section>
<section class="section has-background-white-bis">
    <div class="container">
        <div class="columns">
            <div class="column is-8-tablet is-9-desktop">
                <div class="masonry is-1-tablet is-2-desktop">
                    {% for category in category_list %}
                    <div class="masonry-item">
                        {% include 'helpdesk/includes/category-detail-card.html' with category=category show_featured=True %}
                    </div>
                    {% endfor %}
                </div>
            </div>
            <div class="column is-4-tablet is-3-desktop">
                <div class="card glossary">
                    <div class="card-header">
                        <a href="{% url 'helpdesk:glossary' %}" class="card-header-title">Glossary</a>
                    </div>
                    <div class="card-content">
                        {% include 'helpdesk/includes/term-list-inline.html' with term_list=glossary %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

camp/templates/helpdesk/search.html
{% extends 'helpdesk/base.html' %}
{% load static %}
{% load sjvair %}

{% block title %}Search Results for "{{ search_query }}" | {{ block.super }}{% endblock %}

{% block body-class %}{{ block.super }} search{% endblock %}

{% block breadcrumb-list %}
    <li class="is-active">
        <a href="{% url 'helpdesk:search' %}">Search</a>
    </li>
{% endblock %}

{% block content %}
<section class="section">
    <div class="container">
        <div class="content">
            <h1>
                <span>Search results for "{{ search_query }}"</span>
                <span class="is-italic has-text-grey is-size-5 has-text-weight-normal">({{ article_results|length }} result{{ article_results|length|pluralize }} found)</span>
            </h1>
        </div>
        <div class="columns">
            <div class="column is-9-desktop">
                {% if article_results %}
                <div class="list article-list-inline">
                    {% for article in article_results %}
                    <div class="list-item box">
                        <div class="list-item-image">
                            <span class="icon">
                                <span class="fal fa-lg fa-fw fa-file-alt"></span>
                            </span>
                        </div>
                        <div class="list-item-content">
                            <a href="{{ article.get_absolute_url }}" class="list-item-title">
                                <span>{{ article.title }}</span>
                            </a>
                            <div class="list-item-description">{{ article.headline|safe }}</div>
                        </div>
                    </div>
                    {% endfor %}
                </div>

                {% else %}
                <div class="box">
                    <p class="lead">Sorry, we couldn't find anything matching your search query.</p>
                </div>
                {% endif %}
            </div>

            <div class="column is-3-desktop">
                {% if term_results %}
                <h2 class="is-size-4 has-text-weight-semibold">Glossary Results</h2>
                {% include 'helpdesk/includes/term-list-inline.html' with term_list=term_results %}
                {% endif %}

                {% include 'helpdesk/includes/cta-contact.html' %}
            </div>
        </div>
    </div>
</section>
{% endblock %}