aqm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from aqm.apps.sensors.urls import urlpatterns as sensor_urls

urlpatterns = [
    path('sensors', include('aqm.apps.sensors.urls', namespace='sensors')),

    # Admin-y stuff
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path('batcave/', admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls))
    ]
    # urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

camp/api/urls.py
from django.urls import include, path
from django.views import generic

from resticus.views import get_schema_view

from .v1 import urls as urls_v1_0

app_name = 'api'

schema_v1_0 = get_schema_view(
    title="SJVAir API v1.0", prefix="/api/1.0/", urlconf=urls_v1_0
)

urlpatterns = [
    path('2.0/', include('camp.api.v2.urls', namespace='v2')),

    path('1.0/', include('camp.api.v1.urls', namespace='v1')),
    path('1.0/schema/', schema_v1_0, name="schema_v1_0"),
    path('1.0/swagger/',
        generic.TemplateView.as_view(
            template_name="swagger/index.html",
            extra_context={"schema_url": "api:schema_v1_0"},
        ),
        name="swagger",
    ),
]

camp/api/v1/urls.py
from django.urls import include, path

from . import endpoints
from .alerts.endpoints import SubscriptionList

app_name = 'api'

urlpatterns = [
    path('time/', endpoints.CurrentTime.as_view(), name='current-time'),
    path('alerts/subscriptions/', SubscriptionList.as_view(), name='subscription-list'),

    path('account/', include('camp.api.v1.accounts.urls', namespace='account')),
    path('monitors/', include('camp.api.v1.monitors.urls', namespace='monitors')),
    path('calibrations/', include('camp.api.v1.calibrations.urls', namespace='calibrations')),
    path('marker.png', endpoints.MapMarker.as_view(), name='marker'),

]

camp/apps/accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import include, path, reverse_lazy

import vanilla

from . import forms, views

from camp.apps.alerts.views import AlertList, SubscriptionList

urlpatterns = [
    # Login and signup
    path('login/', auth_views.LoginView.as_view(
        authentication_form=forms.AuthenticationForm,
    ), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignupView.as_view(), name='signup'),

    # Account management
    path('', views.ProfileView.as_view(), name='profile'),

    path('alerts/', AlertList.as_view(), name='alerts'),
    path('subscriptions/', SubscriptionList.as_view(), name='subscriptions'),

    path('phone/', views.SendPhoneVerification.as_view(), name='phone-verify-send'),
    path('phone/verify/', views.SubmitPhoneVerification.as_view(), name='phone-verify-submit'),

    path('password/', auth_views.PasswordChangeView.as_view(
        success_url=reverse_lazy('account:password-change-done'),
    ), name='password-change'),
    path('password/done/', auth_views.PasswordChangeDoneView.as_view(), name='password-change-done'),

    # Password reset
    path('password/reset/', views.PasswordReset.as_view(), name='password-reset'),
    path('password/reset/confirm/', views.PasswordResetConfirm.as_view(), name='password-reset-confirm'),
    path('password/reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password-reset-complete'),
]

camp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path

from camp.utils import views

admin.site.site_title = "SJVAir Admin"
admin.site.site_header = "SJVAir Admin"

urlpatterns = [
    path('api/', include('camp.api.urls', namespace='api')),
    path('account/', include(('camp.apps.accounts.urls', 'account'), namespace='account')),
    path('contact/', include(('camp.apps.contact.urls', 'contact'), namespace='contact')),
    path('support/', include(('camp.apps.helpdesk.urls', 'helpdesk'), namespace='helpdesk')),
    path('app/', views.GetTheApp.as_view(), name='app'),

    # @sjvair/monitor-map specific routes
    path('monitor/<monitor_id>/', views.PageTemplate.as_view(template_name='pages/index.html')),
    path('widget/', views.RenderStatic.as_view(static_file='widget/index.html')),

    path('prose/', include('prose.urls')),

    # Admin-y stuff
    path('system-status/', include('health_check.urls')),
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path('batcave/stats.json', views.AdminStats.as_view(), name='admin-stats'),
    path('batcave/flush-queue/<str:key>/', views.FlushQueue.as_view(), name='flush-queue'),
    path('batcave/silk/', include('silk.urls', namespace='silk')),
    path('batcave/', admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Catch-all to render templates based on the path
urlpatterns += [re_path('^', views.PageTemplate.as_view())]

camp/apps/accounts/models.py
import random
import string

from django.conf import settings
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.core.cache import cache
from django.db import models
from django.utils import timezone
from django.utils.functional import cached_property
from django.utils.translation import gettext_lazy as _

from dirtyfields import DirtyFieldsMixin
from django_smalluuid.models import SmallUUIDField, uuid_default
from model_utils import Choices
from nameparser.parser import HumanName
from phonenumber_field.modelfields import PhoneNumberField

from camp.apps.accounts import managers
from camp.apps.accounts import tasks
from camp.utils.fields import NullEmailField


class User(AbstractBaseUser, PermissionsMixin, DirtyFieldsMixin, models.Model):
    LANGUAGES = Choices(*settings.LANGUAGES)

    id = SmallUUIDField(
        default=uuid_default(),
        primary_key=True,
        db_index=True,
        editable=False,
        verbose_name='ID'
    )
    full_name = models.CharField(_('Full name'), max_length=100)
    email = NullEmailField(_('Email address'), unique=True, blank=True, null=True, db_index=True)
    phone = PhoneNumberField(_('Phone number'), unique=True, db_index=True, help_text="Your cell phone number for receiving air quality text alerts.")
    phone_verified = models.BooleanField(default=False)
    language = models.CharField(_('Preferred Language'), max_length=5, choices=LANGUAGES, default=LANGUAGES.en)

    # Normally provided by auth.AbstractUser, but we're not using that here.
    date_joined = models.DateTimeField(_('Date joined'), default=timezone.now, editable=False)
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as '
            'active. Unselect this instead of deleting accounts.'
        )
    )
    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_(
            'Designates whether the user can log into this admin site.'
        )
    )

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'phone'
    REQUIRED_FIELDS = ['full_name']

    objects = managers.UserManager()

    class Meta:
        ordering = ('-date_joined',)

    def __str__(self):
        return str(self.name)

    def get_name(self):
        name = HumanName(self.full_name)
        name.capitalize()
        return name

    def set_name(self, value):
        self.full_name = value
        del self.name

    name = cached_property(get_name)
    name.setter = set_name

    def get_short_name(self):
        return self.name.first

    def get_full_name(self):
        return self.name

    @property
    def phone_verification_rate_limit_key(self):
        return f'phone-rate-limit:{self.phone}'

    @property
    def phone_verification_code_key(self):
        return f'phone-code:{self.phone}'

    def check_phone_verification_rate_limit(self):
        cache_key = self.phone_verification_rate_limit_key
        return cache.get(cache_key, default=False)

    def set_phone_verification_rate_limit(self):
        cache_key = self.phone_verification_rate_limit_key
        expires = settings.PHONE_VERIFICATION_RATE_LIMIT * 60
        cache.set(cache_key, True, expires)

    def send_phone_verification_code(self):
        expires = settings.PHONE_VERIFICATION_CODE_EXPIRES * 60
        code = ''.join([
            random.choice(string.digits) for x
            in range(settings.PHONE_VERIFICATION_CODE_DIGITS)
        ])
        cache.set(self.phone_verification_code_key, code, expires)
        message = f'SJVAir – Verification Code: {code}'
        self.send_sms(message, verify=False)  # Don't do a verification check

    def check_phone_verification_code(self, code):
        cached_code = cache.get(self.phone_verification_code_key)
        return code == cached_code

    def send_sms(self, message, verify=True):
        if self.phone and (self.phone_verified or not verify):
            return tasks.send_sms_message(self.phone, message)
        return False

camp/apps/alerts/models.py
from datetime import timedelta

from django.conf import settings
from django.core.exceptions import ValidationError
from django.db import models
from django.db.models import Avg
from django.utils import timezone
from django.utils.functional import cached_property
from django.utils.translation import gettext as _

from django_smalluuid.models import SmallUUIDField, uuid_default
from model_utils import Choices
from model_utils.models import TimeStampedModel

from camp.apps.entries.fields import EntryTypeField
from camp.apps.entries.levels import AQLevel


class Subscription(TimeStampedModel):
    LEVELS = Choices(  # Legacy
        ('unhealthy_sensitive', 'Unhealthy for Sensitive Groups'),
        ('unhealthy', 'Unhealthy'),
        ('very_unhealthy', 'Very Unhealthy'),
        ('hazardous', 'Hazardous'),
    )

    id = SmallUUIDField(
        default=uuid_default(),
        primary_key=True,
        db_index=True,
        editable=False,
        verbose_name='ID'
    )

    user = models.ForeignKey('accounts.User',
        related_name='subscriptions',
        on_delete=models.CASCADE,
    )

    monitor = models.ForeignKey('monitors.Monitor',
        related_name='subscriptions',
        on_delete=models.CASCADE,
    )

    level = models.CharField(max_length=25, choices=AQLevel.choices)

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'monitor'],
                name='user_subscriptions'
            )
        ]

        ordering = ['monitor__name']

    def __str__(self):
        return f'{self.user_id} : {self.monitor_id} @ {self.level}'

    def clean(self):
        super().clean()
        self.level = self.level.lower()


class Alert(TimeStampedModel):
    id = SmallUUIDField(
        default=uuid_default(),
        primary_key=True,
        db_index=True,
        editable=False,
        verbose_name='ID'
    )

    monitor = models.ForeignKey('monitors.Monitor', related_name='alerts', on_delete=models.CASCADE)
    entry_type = EntryTypeField()

    start_time = models.DateTimeField()
    end_time = models.DateTimeField(blank=True, null=True)

    latest = models.OneToOneField(
        'alerts.AlertUpdate',
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='+'
    )

    class Meta:
        ordering = ['-start_time']

    def __str__(self):
        return f'Alert for {self.monitor_id} ({self.entry_type}) @ {self.start_time}'

    @cached_property
    def entry_model(self):
        return EntryTypeField.get_model_map().get(self.entry_type)

    def get_average(self, hours=1):
        end_time = timezone.now()
        start_time = end_time - timedelta(hours=hours)
        return (self.monitor.entries
            .filter(timestamp__range=(start_time, end_time))
            .aggregate(average=Avg('pm25'))['average']
        )

    def create_update(self, level, **kwargs):
        update = AlertUpdate.objects.create(
            alert_id=self.pk,
            level=level.key,
            **kwargs,
        )
        self.send_notifications(update.get_level())
        return update

    def send_notifications(self, level):
        # If SMS alerts are disbaled, do nothing.
        if not settings.SEND_SMS_ALERTS:
            return

        icon = '✅' if level == AQLevel.scale.GOOD else '⚠️'
        message = '\n'.join([
            _('{icon} Air Quality Alert for {name} in {county} County').format(
                icon=icon,
                name=self.monitor.name,
                county=self.monitor.county,
            ),
            f'{self.entry_model.label}: {level.label}',
            f'{level.guidance}\n' or '',
            f'🔗 https://sjvair.com{self.monitor.get_absolute_url()}',
        ])

        queryset = (Subscription.objects
            .filter(monitor_id=self.monitor.pk)
            .select_related('user')
        )

        for sub in queryset:
            sub_level = AQLevel.scale[sub.level.upper()]
            if level >= sub_level:
                sub.user.send_sms(message)


class AlertUpdate(TimeStampedModel):
    alert = models.ForeignKey('alerts.Alert', related_name='updates', on_delete=models.CASCADE)
    timestamp = models.DateTimeField(default=timezone.now)
    level = models.CharField(max_length=25)

    class Meta:
        get_latest_by = 'timestamp'
        ordering = ['timestamp']

    def __str__(self):
        return f'AlertUpdate for {self.alert_id} @ {self.timestamp} => {self.level}'

    def get_level(self):
        return self.alert.entry_model.Levels[self.level]

    def clean(self):
        if not self.alert.entry_model or not self.alert.entry_model.Levels:
            raise ValidationError('This alert entry type does not support alert levels.')

        if self.alert.entry_model.Levels.lookup(self.level) is None:
            raise ValidationError(f'{self.level} is not a valid alert level for {self.alert.entry_type.label}.')

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if not self.alert.latest or self.alert.latest.timestamp < self.timestamp:
            self.alert.latest_id = self.pk
            self.alert.save(update_fields=['latest_id'])

camp/apps/integrate/hms_smoke/models.py
from django.contrib.gis.db import models as gis_models
from django.db import models
from django_smalluuid.models import SmallUUIDField, uuid_default


"""
Defines the database for holding HMS Wildfire smoke data.
This includes:
    the start/end time of the plume: stored as datetime objects
    satellite: the satellite used to observe the smoke
    density: density of smoke plume ("Light", "Medium", or "Heavy")
    geometry: polygonal smoke region in standard GPS coordinates (srid = 4326)
    ID: unique database ID identifier   
"""


class Smoke(models.Model):
    class Density(models.TextChoices):
        LIGHT = 'light', 'Light'
        MEDIUM = 'medium', 'Medium'
        HEAVY = 'heavy', 'Heavy'
    
    id = SmallUUIDField(
        default=uuid_default(),
        primary_key=True,
        db_index=True,
        editable=False,
        verbose_name='ID'
    )
    date = models.DateField(null=True)
    satellite = models.CharField(max_length=20)
    start = models.DateTimeField(null=True)
    end = models.DateTimeField(null=True) 
    density = models.CharField(max_length=10, choices=Density.choices, default=Density.LIGHT)
    geometry = gis_models.MultiPolygonField(srid=4326)
    is_final = models.BooleanField(default=False)

camp/api/v1/forms.py
import re

from django import forms
from django.core.validators import RegexValidator
from django.utils.translation import gettext_lazy as _

COLOR_RE = re.compile('^([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')
color_validator = RegexValidator(COLOR_RE, _('Enter a valid color.'), 'invalid')


class MarkerForm(forms.Form):
    size = forms.IntegerField(initial=24, required=False)
    shape = forms.ChoiceField(choices=[
        (x, x) for x in ('square', 'circle', 'polygon')
        ], initial='circle', required=False)
    fill_color = forms.CharField(validators=[color_validator], initial='777', required=False)
    border_color = forms.CharField(validators=[color_validator], initial='000', required=False)
    border_size = forms.IntegerField(initial=0, required=False)
    sides = forms.IntegerField(initial=3, required=False)

    def get_defaults(self):
        return {key: field.initial for key, field in self.fields.items()}

    def get_data(self):
        data = self.get_defaults()
        if self.is_valid():
            for key, value in self.cleaned_data.items():
                if value:
                    data[key] = value
        return data

camp/api/v1/monitors/forms.py
from django import forms

from camp.apps.monitors.models import Entry


class EntryForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['timestamp'].required = False

        for key in Entry.ENVIRONMENT:
            self.fields[key].required = False

    class Meta:
        model = Entry
        fields = ['timestamp', 'sensor'] + Entry.ENVIRONMENT

camp/templates/pages/alerts.html
{% extends 'page.html' %}
{% load static %}
{% load sjvair %}

{% block title %}SMS Alerts | {{ block.super }}{% endblock %}

{% block body-class %}alerts{% endblock %}

{% block main %}
<section class="section hook">
    <div class="container">
        <div class="columns is-vcentered">
            <div class="column is-4-tablet is-3-desktop mobile-screenshots">
                <img src="{% static 'img/text-alert.png' %}" class="is-responsive" alt="" />
            </div>
            <div class="column is-7-desktop content">
                <h1 class="is-size-1">Live air quality alerts, straight to your phone.</h1>
                <p class="lead">Get notified when the air is bad in your area with
                    the only real-time air quality alert system in California.</p>
                {% if not user.is_authenticated %}
                <p class="buttons">
                    <a class="button is-white" href="{% url 'account:login' %}">Login to your account</a>
                    <a class="button is-blue" href="{% url 'account:signup' %}">Sign up for air quality alerts</a>
                </p>
                {% endif %}
            </div>
        </div>
    </div>
</section>

<section class="section">
    <div class="container">
        <div class="content">
            <h1 class="is-size-1 title has-text-centered">How does it work?</h1>
        </div>

        {% load_datafile 'alerts-boxes.yaml' as alerts_boxes %}
        {% for box in alerts_boxes %}
        <div class="columns is-centered">
            <div class="column is-10-tablet is-10-desktop">
                <div class="box mb-6">
                    <div class="columns is-reversed is-multiline is-centered">
                        <div class="column is-12-tablet is-7-desktop">
                            <div class="content">
                                <h2>{{ box.title }}</h3>
                                <p class="lead">{{ box.content }}</p>
                            </div>
                        </div>
                        <div class="column is-10-tablet is-5-desktop">
                            <figure class="image is-3by2">
                                <img src="{% static box.image %}" alt="" />
                            </figure>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- <div class="card is-horizontal mb-5">
            <div class="card-image">
                <figure class="image is-3by2">
                    <img src="{% static box.image %}" alt="" />
                </figure>
            </div>
            <div class="card-content">
                <div class="content">
                    <h2>{{ box.title }}</h3>
                    <p class="lead">{{ box.content }}</p>
                </div>
            </div>
        </div> -->
        {% endfor %}
    </div>
</section>
{% endblock %}

{% block javascripts %}
{% endblock %}

camp/templates/pages/api.html
{% extends 'page.html' %}
{% load cache %}
{% load static %}
{% load sjvair %}

{% block title %}API | {{ block.super }}{% endblock %}

{% block body-class %}api{% endblock %}

{% block main %}
<section class="section hook">
    <div class="container">
        <div class="content">
            <h1>API Endpoint Reference</h1>
        </div>
    </div>
</section>

<section class="section">
    <div class="container">
        <div class="tabs-with-content">
            <div class="tabs">
                <ul>
                    <li><a>Monitor List</a></li>
                    <li><a>Monitor Detail</a></li>
                    <li><a>Entries List</a></li>
                    <li><a>Entries CSV</a></li>
                </ul>
            </div>
            <div>
                <section class="tab-content">
                    {% api_docs "/api/1.0/monitors/" '{"name__icontains": "Root Access"}' %}
                </section>
                <section class="tab-content">
                    {% api_docs "/api/1.0/monitors/xudEmbncQ7iqwy3sZ0jZvQ/" %}
                </section>
                <section class="tab-content">
                    {% api_docs "/api/1.0/monitors/xudEmbncQ7iqwy3sZ0jZvQ/entries/" %}
                </section>
                <section class="tab-content">
                    {% api_docs "/api/1.0/monitors/xudEmbncQ7iqwy3sZ0jZvQ/entries/csv/" '{"timestamp__gte": "2021-01-18", "timestamp__lte": "2021-01-19"}' %}
                </section>
            </div>
        </div>
    </div>
</section>
{% endblock %}

{% block javascripts %}
    <script type="text/javascript" src="{% static 'js/bulma-tabs.js' %}"></script>
{% endblock %}

camp/templates/pages/app.html
{% extends 'page.html' %}
{% load static %}
{% load sjvair %}

{% block title %}Get the SJVAir App! | {{ block.super }}{% endblock %}

{% block body-class %}app{% endblock %}

{% block main %}
<section class="section hook">
    <div class="container">
        <div class="columns is-centered is-vcentered">
            <div class="column is-6-desktop">
                <h1 class="title">Get to know the air you're breathing.</h1>
                <p class="lead">Download the SJVAir app and stay on top of your local air quality and weather. For iOS and Android.</p>

                <ul class="badges is-inline">
                    <li><a href="{{ settings.APP_URL_IPHONE }}">
                        <img src="{% static 'img/app/apple-app-store-badge.svg' %}" alt="Download for iPhone" />
                    </a></li>
                    <li><a href="{{ settings.APP_URL_ANDROID }}">
                        <img src="{% static 'img/app/google-play-store-badge.svg' %}" alt="Download for Android" />
                    </a></li>
                </ul>
                <div class="card qr-code">
                    <div class="card-image">
                        <figure class="image is-square">
                            <img src="{% static 'img/sjvair-app-qr-code.svg' %}" alt="QR Code" />
                        </figure>
                    </div>
                    <header class="card-header">
                        <span class="card-header-title is-centered">Scan to Download</span>
                    </header>
                </div>
            </div>
            <div class="column is-3-desktop">
                <div class="crossfade">
                    <img src="{% static 'img/app/my-air.png' %}" alt="" class="is-responsive current" />
                    <img src="{% static 'img/app/weather.png' %}" alt="" class="is-responsive" />
                    <img src="{% static 'img/app/monitor-map.png' %}" alt="" class="is-responsive" />
                </div>
            </div>
        </div>
    </div>
</section>

<section class="section has-background-light">
    <div class="container">
        <h2 class="title has-text-centered mb-6">App Features</h2>

        <div class="columns is-mobile is-multiline is-centered">
            <div class="column is-10-mobile is-5-tablet is-3-desktop has-text-centered">
                <div class="box">
                    <span class="icon is-large has-text-primary mb-4">
                        <span class="fa-duotone fa-3x fa-smog"
                            style="--fa-primary-color: RosyBrown;
                                --fa-secondary-color: Tan;
                                --fa-secondary-opacity: 1.0;"></span>
                    </span>
                    <h3 class="title is-size-5 mb-1">Check Local Air Quality</h3>
                    <p>Stay informed with instant readings geolocated to your position.</p>
                </div>
            </div>

            <div class="column is-10-mobile is-5-tablet is-3-desktop has-text-centered">
                <div class="box">
                    <span class="icon is-large has-text-info mb-4">
                        <span class="fa-duotone fa-3x fa-map-marked-alt"
                            style="--fa-primary-color: Crimson;
                                --fa-secondary-color: CadetBlue;
                                --fa-secondary-opacity: 1.0;"></span>
                    </span>
                    <h3 class="title is-size-5 mb-1">Explore the Map</h3>
                    <p>Explore a live map showing monitors across the San Joaquin Valley.</p>
                </div>
            </div>

            <div class="column is-10-mobile is-5-tablet is-3-desktop has-text-centered">
                <div class="box">
                    <span class="icon is-large has-text-warning mb-4">
                        <span class="fa-duotone fa-3x fa-cloud-sun"
                            style="--fa-primary-color: Silver;
                                --fa-secondary-color: Gold;
                                --fa-secondary-opacity: 1.0;"></span>
                    </span>
                    <h3 class="title is-size-5 mb-1">See Local Weather</h3>
                    <p>Check temperature, humidity, and conditions alongside air quality.</p>
                </div>
            </div>

            <div class="column is-10-mobile is-5-tablet is-3-desktop has-text-centered">
                <div class="box">
                    <span class="icon is-large has-text-danger mb-4">
                        <span class="fa-duotone fa-3x fa-mobile-vibrate"
                            style="--fa-primary-color: DodgerBlue;
                                --fa-secondary-color: DimGray;
                                --fa-secondary-opacity: 1.0;"></span>
                    </span>
                    <h3 class="title is-size-5 mb-1">Get Bad Air Quality Alerts</h3>
                    <p>Get notified when pollutants reach levels that matter to you.</p>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

{% block javascripts %}
<script type="text/javascript" src="{% static 'js/crossfade.js' %}"></script>
{% endblock %}

camp/templates/pages/host.html
{% extends 'page.html' %}
{% load static %}
{% load sjvair %}

{% block title %}Help Monitor the Air in Your Community | {{ block.super }}{% endblock %}

{% block body-class %}host{% endblock %}

{% block content %}
<section class="section has-background-light">
    <div class="container">
        <script type="text/javascript" src="https://form.jotform.com/jsform/253216218368054"></script>
    </div>
</section>
{% endblock %}

{% block javascripts %}

{% endblock %}

camp/templates/pages/index.html
{% extends 'page.html' %}
{% load static %}

{# @sjvair/monitor-map #}
{% block extra-head %}
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
<link type="text/css" rel="stylesheet" href="{% static 'monitor-map/sjvairMonitorMap.css' %}" />
<script type="module" src="{% static 'monitor-map/sjvairMonitorMap.js' %}" async defer></script>
{% endblock %}

{% block title %}{{ block.super }}{% endblock %}

{% block body-class %}map{% endblock %}

{% block main %}
<div id="SJVAirMonitorMap"></div>
{% endblock %}

{# No footer on the homepage #}
{% block footer %}{% endblock %}

{% block javascripts %}
<script type="text/javascript">
    window.GOOGLE_MAPS_API_KEY = "{{ settings.GOOGLE_MAPS_API_KEY }}";
    window.USER = {
        id: {% if user.pk %}"{{ user.pk }}"{% else %}null{% endif %},
        name: "{{ user.name }}",
        email: "{{ user.email }}",
        is_authenticated: {{ user.is_authenticated|lower }},
        is_anonymous: {{ user.is_anonymous|lower }}
    };
</script>


{% endblock %}